"""
crop_params.py
==============
Crop-specific hyperparameters for Tamil Nadu crops.
Novel addition: Coconut with deep root depth, micro-sprinkler,
175L/day water requirement — not in any existing fog irrigation paper.
"""

CROP_PARAMS = {

    "Coconut": {
        "fc":                    0.45,
        "pwp":                   0.18,
        "optimal_low":           0.28,
        "optimal_high":          0.40,
        "water_per_day_L":       175,
        "root_depth_m":          2.5,
        "canopy_radius_m":       3.5,
        "tree_height_m":         15.0,
        "spacing_m":             7.5,
        "sprinkler_type":        "micro_sprinkler",
        "optimal_tilt_deg":      25,
        "nozzle_pressure_kpa":   250,
        "nozzle_diameter_mm":    5.0,
        "rotation_speed_rpm":    0.5,
        "irrigation_duration_min": 45,
        "ky":                    1.10,
        "field_size_m":          (30, 30),
        "growth_stages": {
            "seedling": {"fc": 0.38, "pwp": 0.15, "water_L": 30},
            "young":    {"fc": 0.40, "pwp": 0.16, "water_L": 80},
            "mature":   {"fc": 0.45, "pwp": 0.18, "water_L": 175},
            "bearing":  {"fc": 0.45, "pwp": 0.18, "water_L": 200},
        },
        "color": "#8B4513",
    },

    "Wheat": {
        "fc":                    0.34,
        "pwp":                   0.14,
        "optimal_low":           0.22,
        "optimal_high":          0.29,
        "water_per_day_L":       6,
        "root_depth_m":          1.0,
        "canopy_radius_m":       0.2,
        "tree_height_m":         0.8,
        "spacing_m":             0.15,
        "sprinkler_type":        "overhead_sprinkler",
        "optimal_tilt_deg":      45,
        "nozzle_pressure_kpa":   200,
        "nozzle_diameter_mm":    4.0,
        "rotation_speed_rpm":    1.0,
        "irrigation_duration_min": 20,
        "ky":                    0.85,
        "field_size_m":          (20, 20),
        "growth_stages": {
            "germination": {"fc": 0.30, "pwp": 0.12, "water_L": 3},
            "tillering":   {"fc": 0.34, "pwp": 0.14, "water_L": 6},
            "heading":     {"fc": 0.34, "pwp": 0.14, "water_L": 8},
            "maturity":    {"fc": 0.30, "pwp": 0.12, "water_L": 4},
        },
        "color": "#DAA520",
    },

    "Potato": {
        "fc":                    0.38,
        "pwp":                   0.16,
        "optimal_low":           0.25,
        "optimal_high":          0.32,
        "water_per_day_L":       8,
        "root_depth_m":          0.6,
        "canopy_radius_m":       0.3,
        "tree_height_m":         0.5,
        "spacing_m":             0.30,
        "sprinkler_type":        "overhead_sprinkler",
        "optimal_tilt_deg":      40,
        "nozzle_pressure_kpa":   200,
        "nozzle_diameter_mm":    4.0,
        "rotation_speed_rpm":    1.0,
        "irrigation_duration_min": 25,
        "ky":                    1.10,
        "field_size_m":          (20, 20),
        "growth_stages": {
            "emergence":  {"fc": 0.35, "pwp": 0.14, "water_L": 5},
            "vegetative": {"fc": 0.38, "pwp": 0.16, "water_L": 8},
            "tuber":      {"fc": 0.38, "pwp": 0.16, "water_L": 10},
            "maturity":   {"fc": 0.32, "pwp": 0.14, "water_L": 4},
        },
        "color": "#DEB887",
    },

    "Tomato": {
        "fc":                    0.35,
        "pwp":                   0.15,
        "optimal_low":           0.23,
        "optimal_high":          0.30,
        "water_per_day_L":       7,
        "root_depth_m":          0.8,
        "canopy_radius_m":       0.4,
        "tree_height_m":         1.2,
        "spacing_m":             0.60,
        "sprinkler_type":        "overhead_sprinkler",
        "optimal_tilt_deg":      42,
        "nozzle_pressure_kpa":   200,
        "nozzle_diameter_mm":    4.0,
        "rotation_speed_rpm":    1.0,
        "irrigation_duration_min": 22,
        "ky":                    1.05,
        "field_size_m":          (15, 15),
        "growth_stages": {
            "seedling":   {"fc": 0.32, "pwp": 0.13, "water_L": 3},
            "vegetative": {"fc": 0.35, "pwp": 0.15, "water_L": 7},
            "flowering":  {"fc": 0.35, "pwp": 0.15, "water_L": 9},
            "fruiting":   {"fc": 0.35, "pwp": 0.15, "water_L": 8},
        },
        "color": "#FF6347",
    },

    "Chilli": {
        "fc":                    0.33,
        "pwp":                   0.14,
        "optimal_low":           0.21,
        "optimal_high":          0.28,
        "water_per_day_L":       5,
        "root_depth_m":          0.5,
        "canopy_radius_m":       0.25,
        "tree_height_m":         0.6,
        "spacing_m":             0.45,
        "sprinkler_type":        "overhead_sprinkler",
        "optimal_tilt_deg":      43,
        "nozzle_pressure_kpa":   200,
        "nozzle_diameter_mm":    4.0,
        "rotation_speed_rpm":    1.0,
        "irrigation_duration_min": 18,
        "ky":                    0.90,
        "field_size_m":          (15, 15),
        "growth_stages": {
            "seedling":   {"fc": 0.30, "pwp": 0.12, "water_L": 2},
            "vegetative": {"fc": 0.33, "pwp": 0.14, "water_L": 5},
            "flowering":  {"fc": 0.33, "pwp": 0.14, "water_L": 6},
            "fruiting":   {"fc": 0.30, "pwp": 0.13, "water_L": 4},
        },
        "color": "#FF4500",
    },
}

# 9 plots — coconut added as plot_00
PLOT_ASSIGNMENTS = [
    {"plot": "plot_00", "crop": "Coconut", "soil": "Red Soil",      "stage": "bearing"},
    {"plot": "plot_01", "crop": "Wheat",   "soil": "Black Soil",    "stage": "tillering"},
    {"plot": "plot_02", "crop": "Potato",  "soil": "Alluvial Soil", "stage": "tuber"},
    {"plot": "plot_03", "crop": "Tomato",  "soil": "Red Soil",      "stage": "fruiting"},
    {"plot": "plot_04", "crop": "Chilli",  "soil": "Clay Soil",     "stage": "flowering"},
    {"plot": "plot_05", "crop": "Wheat",   "soil": "Loam Soil",     "stage": "heading"},
    {"plot": "plot_06", "crop": "Potato",  "soil": "Chalky Soil",   "stage": "vegetative"},
    {"plot": "plot_07", "crop": "Tomato",  "soil": "Sandy Soil",    "stage": "flowering"},
    {"plot": "plot_08", "crop": "Chilli",  "soil": "Black Soil",    "stage": "fruiting"},
]
